### ISSUE TITLE
automated OpenAPI are currently failing

### ISSUE THREAD

**Issue by gr2m** [octokit/plugin-paginate-rest.js#301]
e.g. https://github.com/octokit/plugin-paginate-rest.js/runs/2396088102?check_suite_focus=true

```
RequestError [HttpError]: request to http://localhost:3000/api/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:3000
    at /home/runner/work/plugin-paginate-rest.js/plugin-paginate-rest.js/node_modules/@octokit/request/dist-node/index.js:109:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/runner/work/plugin-paginate-rest.js/plugin-paginate-rest.js/scripts/update-endpoints/fetch-json.js:35:27) {
  status: 500,
  headers: {},
  request: {
    method: 'POST',
    url: 'http://localhost:3000/api/graphql',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-graphql.js/4.6.1 Node.js/14.16.1 (linux; x64)',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"query":"\\n  query($version: String) {\\n    endpoints(version: $version) {\\n      url\\n      id\\n      scope\\n      documentationUrl\\n      renamed {\\n        note\\n      }\\n      responses {\\n        code\\n        schema\\n      }\\n    }\\n  }\\n","variables":{"version":"2.16.2"}}'
  }
}
```

The GraphQL server fails on Vercel with

```
[ERROR] [1619021004881] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413
```

It's most likely an out-of-memory problem. The query includes response schemas which are huge now, probably too big for Vercel functions to return in a single respones. The `scripts/update-endpoints/typescript.js` looks into the response schema to see if the server responds with an array at the root, or with an object that includes an array key. This is necessary to normalize the responses for the pagination plugin.

To workaround this, we could implement this server side and export a new key that can be queried, that way we don't need to return the entire JSON schemas for all responses

**Comment by gr2m** [comment]
I created https://github.com/gr2m/github-openapi-graphql-query as a replacement for the GraphQL server

List of repositories that need to be updated

- [ ] [octokit/plugin-enterprise-cloud.js](https://github.comoctokit/plugin-enterprise-cloud.js)
- [ ] [octokit/plugin-enterprise-server.js](https://github.comoctokit/plugin-enterprise-server.js)
- [ ] [octokit/plugin-paginate-rest.js](https://github.comoctokit/plugin-paginate-rest.js)
- [ ] [octokit/plugin-rest-endpoint-methods.js](https://github.comoctokit/plugin-rest-endpoint-methods.js)
- [ ] [octokit/plugin-throttling.js](https://github.comoctokit/plugin-throttling.js)
- [ ] [octokit/types.ts](https://github.comoctokit/types.ts)
